name: "nlw-connect"

services:
  mysql:
    image: mysql:8.4
    container_name: nlw-connect-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dev123
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
